### PR TITLE
Hostname filter

### PR DESCRIPTION
**Pull request by Moorviper**
this is a port of the hostname filter from mesh viewer

### CODE REVIEW

**Comment by plumpudding** [comment]
It had a reason that I didn't pick that commit when compiling the base for HopGlass. Is the hostname filter in the meshviewer master?

**Comment by Moorviper** [comment]
this is the same hostname filter as in the mesh viewer with the modification that the nodes are checked if they have a hostname.

+    function run(d) {
 +
 +      if (d.nodeinfo === undefined)
 +        return 0
 +
 +      if (d.nodeinfo)
 +        return d.nodeinfo.hostname.toLowerCase().includes(input.value.toLowerCase())
 +    }
 +
 +    function setRefresh(f) {
 +      refreshFunction = f
 +    }

because with hoppglass not every node have a hostname

**Comment by rotanid** [comment]
@plumpudding would you be so nice to inform us what your reason was?
we really want that feature, too...

**Comment by plumpudding** [comment]
If you want it, you can always cherry-pick the commits. 
I just don't think the feature is ready both by design and implementation.

**Comment by PowerPan** [comment]
What are the reasons for not Applying this Pull Request?

**Comment by Moorviper** [comment]
if you klick the x the filter complete disappear for one reason.

**Comment by plumpudding** [comment]
For example that
It looks ugly and has unexpected behaviour
I am happy with the implementation in https://ffrgb/meshviewer so you will see this soon(TM).

**Comment by PowerPan** [comment]
Yes from the user view it looks good

**Pull request closed without merging**
